# Generated by Django 4.1.5 on 2023-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookPaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('uploadedBy', models.CharField(max_length=50, null=True)),
                ('book', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='booksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('uploadedBy', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('coverImage', models.ImageField(null=True, upload_to='')),
                ('book', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='notesDraftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('note', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='notesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('note', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('isPublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userProfileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('isPrivate', models.BooleanField(default=False)),
            ],
        ),
    ]
