# Generated by Django 4.1.5 on 2023-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalNotebookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('assignment', models.FileField(null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='privateNoteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('uploadedBy', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
