# Generated by Django 4.1.5 on 2023-04-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalNotebookApp', '0002_assignmenttable_privatenotetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatenotetable',
            old_name='approved',
            new_name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='privatenotetable',
            name='amount',
        ),
    ]
