# Generated by Django 4.1.5 on 2023-04-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalNotebookApp', '0003_rename_approved_privatenotetable_isprivate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatenotetable',
            old_name='isPrivate',
            new_name='approved',
        ),
    ]
